### ISSUE TITLE
ModuleNotFoundError: No module named 'oyaml'

### ISSUE THREAD

**Issue by nousername-available** [ostris/ai-toolkit#103]
I cant figure out why its doing this? any ideas? 
I previously had and error "ModuleNotFoundError: No module named 'dotenvl'" but i solved that one with the fallowing commands
"pip install Python-dotenv"

Microsoft Windows [Version 10.0.22631.4037]
(c) Microsoft Corporation. All rights reserved.

F:\Flux Training\ai-toolkit>python run.py config\train_lora_flux_schnell_24gb.yaml
Traceback (most recent call last):
  File "F:\Flux Training\ai-toolkit\run.py", line 22, in <module>
    from toolkit.job import get_job
  File "F:\Flux Training\ai-toolkit\toolkit\job.py", line 3, in <module>
    from toolkit.config import get_config
  File "F:\Flux Training\ai-toolkit\toolkit\config.py", line 5, in <module>
    import oyaml as yaml
ModuleNotFoundError: No module named 'oyaml'

F:\Flux Training\ai-toolkit>

**Comment by martintomov** [comment]
### Look at #56 

"_uninstall oyaml, install pandas, force install and upgrade oyaml again, this worked for me._"

**Comment by brappier** [comment]
do pip install oyaml

**Comment by nousername-available** [comment]
thanks guys. in case somebody else has the same issue i was having i needed to use the fallowing command to install oyaml as the pip install was not working for me. "py -m pip install oyaml"

**Comment by tetsuoo-online** [comment]
> thanks guys. in case somebody else has the same issue i was having i needed to use the fallowing command to install oyaml as the pip install was not working for me. "py -m pip install oyaml"

I see, I guess I have to use -m argument. Otherwise this is what happens every time :
1. start a training
2. get the oyaml error
3. activate venv and install oyaml
4. it says oyaml is already there
5. start the training again and it works
...and by the next training, the same routine happens again x)
I'm scared to touch it right now it's busy training lol I will try again next time

![image](https://github.com/user-attachments/assets/16afd797-b2cc-4fe3-9027-b7b03d772920)
